### ISSUE TITLE
License

### ISSUE THREAD

**Issue by felipefoz** [TomsLabVIEWAdventure/TDD#1]
Hey Tom,

How are you?
I noticed you didn't release this code with License.
For this reason I am asking if you don't mind that I use part of this code in one of my projects.
I'll make sure to cite properly.
Regards,

**Comment by TomsLabVIEWAdventure** [comment]
Hi Felipe,

Thanks for checking. Unless otherwise stated, please feel free to use any code on this account without restriction. I'll try to get around to making sure all the repos are licenced when I get a chance.

Cheers, tom

**Comment by felipefoz** [comment]
Thanks.
It's always good to ask before.
